name = "FourPlayerXORGames"
defaultTargets = ["FourPlayerXORGames"]

[[require]]
name = "QIT"
git = "https://github.com/QuAIR/Lean-QIT.git"
rev = "bb3ada54fa451996df9e197c2be53c2625bc99a3"

[[lean_lib]]
name = "XORGameFormalization"
moreLeanArgs = ["-DautoImplicit=false"]

[[lean_lib]]
name = "FourXOR"
moreLeanArgs = ["-DautoImplicit=false"]

[[lean_lib]]
name = "FourPlayerXORGames"
roots = ["FourPlayerXORGames"]
moreLeanArgs = ["-DautoImplicit=false"]
