/-
Copyright (c) 2026 QuAIR.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QuAIR Team
-/

module

public import XORGameFormalization.Basic
public import XORGameFormalization.Circuit

/-!
# Adaptive rank bounds for four-player XOR-game circuits

This module sharpens the fixed rank-nine cutoff from `Circuit` by counting
only the questions that a clause support actually uses.  The column space is
generated by one constant column and, for each player, all used question
columns except one base column.  Thus its rank is at most

`1 + ∑ a, (usedQuestionsCard query a - 1)`.

Combining this structural bound with
`fullRationalCircuit_card_eq_rank_add_one` gives the boundary constraints
needed at sizes nine and ten, without enumerating clause supports.
-/

@[expose] public section

namespace QIT
namespace XORGame

universe uE

noncomputable section

/-- The local questions that occur for player `a` in the clause support. -/
def usedQuestions {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (a : Fin 4) : Finset (Fin 3) :=
  Finset.univ.image (fun e => query e a)

/-- The number of local questions used by player `a`. -/
def usedQuestionsCard {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (a : Fin 4) : ℕ :=
  (usedQuestions query a).card

@[simp]
theorem mem_usedQuestions {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (a : Fin 4) (q : Fin 3) :
    q ∈ usedQuestions query a ↔ ∃ e : E, query e a = q := by
  classical
  simp [usedQuestions]

/-- Every question appearing in a clause belongs to that player's used set. -/
theorem query_mem_usedQuestions {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (e : E) (a : Fin 4) :
    query e a ∈ usedQuestions query a := by
  simp

/-- A player uses at most the three available local questions. -/
theorem usedQuestionsCard_le_three {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (a : Fin 4) :
    usedQuestionsCard query a ≤ 3 := by
  classical
  have h := Finset.card_le_card
    (Finset.subset_univ (usedQuestions query a))
  simpa [usedQuestionsCard] using h

/-- A player in a nonempty support uses at least one local question. -/
theorem usedQuestionsCard_pos {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause) (a : Fin 4) :
    0 < usedQuestionsCard query a := by
  classical
  let e : E := Classical.choice ‹Nonempty E›
  rw [usedQuestionsCard, Finset.card_pos]
  exact ⟨query e a, query_mem_usedQuestions query e a⟩

private abbrev UsedQuestionGeneratorIndex {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (e₀ : E) :=
  Option (Σ a : Fin 4, ↥((usedQuestions query a).erase (query e₀ a)))

private def usedQuestionRankGenerator {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (e₀ : E) :
    UsedQuestionGeneratorIndex query e₀ → (E → ℚ)
  | none => fun _ => 1
  | some aq => (rationalIncidence query).col (aq.1, aq.2.1)

private theorem sum_used_incidence_columns {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) (a : Fin 4) :
    ∑ q ∈ usedQuestions query a,
        (rationalIncidence query).col (a, q) = fun _ => 1 := by
  classical
  funext e
  simp [rationalIncidence, incidence, usedQuestions]

/--
The rational incidence rank is controlled by the questions actually used:
one constant column is shared by all players, and each player contributes at
most one fewer generator than its number of used questions.
-/
theorem rationalIncidence_rank_le_usedQuestions
    {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause) :
    (rationalIncidence query).rank ≤
      1 + ∑ a : Fin 4, (usedQuestionsCard query a - 1) := by
  classical
  let e₀ : E := Classical.choice ‹Nonempty E›
  rw [Matrix.rank_eq_finrank_span_cols]
  calc
    Module.finrank ℚ
        (Submodule.span ℚ (Set.range (rationalIncidence query).col)) ≤
        Module.finrank ℚ
          (Submodule.span ℚ
            (Set.range (usedQuestionRankGenerator query e₀))) := by
      apply Submodule.finrank_mono
      apply Submodule.span_le.2
      rintro _ ⟨⟨a, q⟩, rfl⟩
      by_cases hused : q ∈ usedQuestions query a
      · by_cases hbase : q = query e₀ a
        · subst q
          have hbaseUsed : query e₀ a ∈ usedQuestions query a :=
            query_mem_usedQuestions query e₀ a
          have hcol :
              (rationalIncidence query).col (a, query e₀ a) =
                usedQuestionRankGenerator query e₀ none -
                  ∑ r ∈ (usedQuestions query a).erase (query e₀ a),
                    (rationalIncidence query).col (a, r) := by
            change (rationalIncidence query).col (a, query e₀ a) =
              (fun _ => 1) -
                ∑ r ∈ (usedQuestions query a).erase (query e₀ a),
                  (rationalIncidence query).col (a, r)
            rw [← sum_used_incidence_columns query a]
            exact eq_sub_of_add_eq'
              (Finset.sum_erase_add
                (usedQuestions query a)
                (fun r => (rationalIncidence query).col (a, r))
                hbaseUsed)
          have hone :
              usedQuestionRankGenerator query e₀ none ∈
                Submodule.span ℚ
                  (Set.range (usedQuestionRankGenerator query e₀)) :=
            Submodule.subset_span ⟨none, rfl⟩
          have herase :
              (∑ r ∈ (usedQuestions query a).erase (query e₀ a),
                (rationalIncidence query).col (a, r)) ∈
                  Submodule.span ℚ
                    (Set.range (usedQuestionRankGenerator query e₀)) := by
            exact Submodule.sum_mem _ fun r hr =>
              Submodule.subset_span
                ⟨some ⟨a, ⟨r, hr⟩⟩, rfl⟩
          rw [hcol]
          exact Submodule.sub_mem _ hone herase
        · exact Submodule.subset_span
            ⟨some ⟨a, ⟨q, Finset.mem_erase.mpr ⟨hbase, hused⟩⟩⟩, rfl⟩
      · have hzero :
            (rationalIncidence query).col (a, q) = 0 := by
          funext e
          have hne : query e a ≠ q := by
            intro heq
            exact hused ((mem_usedQuestions query a q).2 ⟨e, heq⟩)
          simp [rationalIncidence, incidence, hne]
        rw [hzero]
        exact Submodule.zero_mem _
    _ ≤ Fintype.card (UsedQuestionGeneratorIndex query e₀) := by
      simpa only [Set.finrank] using
        (finrank_range_le_card
          (R := ℚ) (usedQuestionRankGenerator query e₀))
    _ = 1 + ∑ a : Fin 4, (usedQuestionsCard query a - 1) := by
      simp only [UsedQuestionGeneratorIndex, Fintype.card_option,
        Fintype.card_sigma, Fintype.card_coe, usedQuestionsCard]
      have hcard : ∀ a : Fin 4,
          ((usedQuestions query a).erase (query e₀ a)).card =
            (usedQuestions query a).card - 1 :=
        fun a => Finset.card_erase_of_mem
          (query_mem_usedQuestions query e₀ a)
      simp_rw [hcard]
      omega

/--
A ten-clause full rational circuit uses all three questions at every player.

Indeed, fullness gives rank nine.  The adaptive rank bound can reach nine only
when all four summands `usedQuestionsCard query a - 1` reach their maximum
value two.
-/
theorem tenClause_fullCircuit_uses_all_questions
    {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause)
    (hcard : Fintype.card E = 10)
    (hCircuit : IsFullRationalCircuit (rationalIncidence query)) :
    ∀ a : Fin 4, usedQuestionsCard query a = 3 := by
  have hcardRank :=
    fullRationalCircuit_card_eq_rank_add_one
      (rationalIncidence query) hCircuit
  have hrank : (rationalIncidence query).rank = 9 := by omega
  have hbound := rationalIncidence_rank_le_usedQuestions query
  rw [hrank] at hbound
  simp only [Fin.sum_univ_succ] at hbound
  norm_num [Fin.ext_iff] at hbound
  have hlast : (Fin.succ (2 : Fin 3) : Fin 4) = 3 := by rfl
  rw [hlast] at hbound
  have h0 := usedQuestionsCard_le_three query (0 : Fin 4)
  have h1 := usedQuestionsCard_le_three query (1 : Fin 4)
  have h2 := usedQuestionsCard_le_three query (2 : Fin 4)
  have h3 := usedQuestionsCard_le_three query (3 : Fin 4)
  intro a
  fin_cases a <;> simp_all <;> omega

/--
Every player in a nine-clause full rational circuit uses at least two
questions.
-/
theorem nineClause_fullCircuit_uses_at_least_two_questions
    {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause)
    (hcard : Fintype.card E = 9)
    (hCircuit : IsFullRationalCircuit (rationalIncidence query)) :
    ∀ a : Fin 4, 2 ≤ usedQuestionsCard query a := by
  have hcardRank :=
    fullRationalCircuit_card_eq_rank_add_one
      (rationalIncidence query) hCircuit
  have hrank : (rationalIncidence query).rank = 8 := by omega
  have hbound := rationalIncidence_rank_le_usedQuestions query
  rw [hrank] at hbound
  simp only [Fin.sum_univ_succ] at hbound
  norm_num [Fin.ext_iff] at hbound
  have hlast : (Fin.succ (2 : Fin 3) : Fin 4) = 3 := by rfl
  rw [hlast] at hbound
  have h0 := usedQuestionsCard_le_three query (0 : Fin 4)
  have h1 := usedQuestionsCard_le_three query (1 : Fin 4)
  have h2 := usedQuestionsCard_le_three query (2 : Fin 4)
  have h3 := usedQuestionsCard_le_three query (3 : Fin 4)
  intro a
  fin_cases a <;> simp_all <;> omega

/-- The players that use all three available local questions. -/
def ternaryPlayers {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) : Finset (Fin 4) :=
  Finset.univ.filter (fun a => usedQuestionsCard query a = 3)

/--
With four players, either at most three pages are ternary or every page is
ternary.
-/
theorem ternaryPlayers_card_le_three_or_all
    {E : Type uE} [Fintype E]
    (query : E → FourByThreeClause) :
    (ternaryPlayers query).card ≤ 3 ∨
      ∀ player : FourByThreePlayer,
        usedQuestionsCard query player = 3 := by
  by_cases hthree : (ternaryPlayers query).card ≤ 3
  · exact Or.inl hthree
  · right
    have hcardLe :
        (ternaryPlayers query).card ≤
          Fintype.card FourByThreePlayer :=
      Finset.card_le_univ _
    have hcard :
        (ternaryPlayers query).card =
          Fintype.card FourByThreePlayer := by
      simp only [FourByThreePlayer, Fintype.card_fin] at hcardLe ⊢
      omega
    have huniv :
        ternaryPlayers query = Finset.univ :=
      Finset.eq_univ_of_card _ hcard
    intro player
    have hmem : player ∈ ternaryPlayers query := by
      rw [huniv]
      simp
    simpa [ternaryPlayers] using hmem

/--
In a nine-clause full rational circuit, at most one player can fail to use all
three questions.
-/
theorem nineClause_fullCircuit_has_at_most_one_nonternary_player
    {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause)
    (hcard : Fintype.card E = 9)
    (hCircuit : IsFullRationalCircuit (rationalIncidence query)) :
    ∃ exceptional : Fin 4, ∀ a ≠ exceptional,
      usedQuestionsCard query a = 3 := by
  have hcardRank :=
    fullRationalCircuit_card_eq_rank_add_one
      (rationalIncidence query) hCircuit
  have hrank : (rationalIncidence query).rank = 8 := by omega
  have hbound := rationalIncidence_rank_le_usedQuestions query
  rw [hrank] at hbound
  simp only [Fin.sum_univ_succ] at hbound
  norm_num [Fin.ext_iff] at hbound
  have h0 := usedQuestionsCard_le_three query (0 : Fin 4)
  have h1 := usedQuestionsCard_le_three query (1 : Fin 4)
  have h2 := usedQuestionsCard_le_three query (2 : Fin 4)
  have h3 := usedQuestionsCard_le_three query (3 : Fin 4)
  have hpair : ∀ a b : Fin 4, a ≠ b →
      usedQuestionsCard query a = 3 ∨
        usedQuestionsCard query b = 3 := by
    intro a b hab
    fin_cases a <;> fin_cases b <;> simp_all <;> omega
  by_cases hall : ∀ a : Fin 4, usedQuestionsCard query a = 3
  · exact ⟨0, fun a _ => hall a⟩
  · push Not at hall
    obtain ⟨exceptional, hexceptional⟩ := hall
    refine ⟨exceptional, ?_⟩
    intro a hne
    exact (hpair exceptional a hne.symm).resolve_left hexceptional

/--
At least three players in a nine-clause full rational circuit use all three
questions.
-/
theorem nineClause_fullCircuit_has_three_ternary_players
    {E : Type uE} [Fintype E] [Nonempty E]
    (query : E → FourByThreeClause)
    (hcard : Fintype.card E = 9)
    (hCircuit : IsFullRationalCircuit (rationalIncidence query)) :
    3 ≤ (ternaryPlayers query).card := by
  obtain ⟨exceptional, hternary⟩ :=
    nineClause_fullCircuit_has_at_most_one_nonternary_player
      query hcard hCircuit
  have hsubset :
      (Finset.univ : Finset (Fin 4)).erase exceptional ⊆
        ternaryPlayers query := by
    intro a ha
    have hne := (Finset.mem_erase.mp ha).1
    simp [ternaryPlayers, hternary a hne]
  calc
    3 = ((Finset.univ : Finset (Fin 4)).erase exceptional).card := by simp
    _ ≤ (ternaryPlayers query).card := Finset.card_le_card hsubset

end

end XORGame
end QIT
